### ISSUE TITLE
mongodb-prebuilt dependency

### ISSUE THREAD

**Issue by jkiimm** [CImrie/mongomem#1]
It is right [mongodb-prebuilt](https://github.com/winfinit/mongodb-prebuilt) module is in `devDependencies`?

When I executed mongomem in ava testing, I got this error.

```bash
Error: Cannot find module 'mongodb-prebuilt'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/somepath/node_modules/mongomem/build/MongoDBServer.js:19:24)
... and so on
```

**Comment by byfoz** [comment]
@jkiimm Thanks for the heads up. I have moved the relevant dependencies to the correct location in package.json and released as v0.1.9.
Let me know if you continue to have issues.
